-- AGGREGATE FUNCTIONS
-- AVG
-- MIN
-- MAX
-- COUNT
-- SUM
-- ORDER BY

SELECT AVG(NETSALES)
FROM ASSIGNMENT;

SELECT MIN(NETSALES)
FROM ASSIGNMENT;

SELECT MAX(NETSALES)
FROM ASSIGNMENT;

SELECT COUNT(NETSALES)
FROM ASSIGNMENT;

SELECT SUM(NETSALES)
FROM ASSIGNMENT;

-- Find the average netsales based on eah region
SELECT REGIONNAME, AVG(NETSALES)
FROM ASSIGNMENT
GROUP BY REGIONNAME;

-- Find the total netsales for each product
SELECT PRODNAME, SUM(NETSALES)
FROM ASSIGNMENT
GROUP BY PRODNAME;

-- Find the minimum netsales for each fiscal qtr
SELECT FISCALQTR, MIN(NETSALES)
FROM ASSIGNMENT
GROUP BY FISCALQTR;

-- After using the GROUP BY clause and want to further filter , you use HAVING instead of WHERE
SELECT FISCALQTR, MIN(NETSALES)
FROM ASSIGNMENT
GROUP BY FISCALQTR
HAVING FISCALQTR IN ('Q1-2016', 'Q2-2016')

-- ORDER BY IS AN AGGREGATE FUNCTION THAT ARRANGES DATA IN ASCENDIND OR DESCENDING ORDER

-- GROUP BY IS USED WHEN AN AGGREGATE FUNCTION IS USED. AFTER A GROUP BY , YOU USE HAVING